# Generated by Django 2.0 on 2018-03-25 18:33

from django.db import migrations, models
import django.db.models.deletion
import randomslugfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_auto_20180309_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('umid', randomslugfield.fields.RandomSlugField(blank=True, editable=False, length=9, max_length=9, primary_key=True, serialize=False, unique=True)),
                ('to_email', models.EmailField(max_length=200)),
                ('from_email', models.EmailField(default='no-reply@makesamai.com', max_length=200)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='SENT', max_length=200)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account')),
            ],
            options={
                'verbose_name_plural': 'Emails',
                'verbose_name': 'Email',
            },
        ),
    ]
