# Generated by Django 2.0 on 2018-03-27 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='account',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='accounts.Account'),
        ),
        migrations.AlterField(
            model_name='email',
            name='from_email',
            field=models.EmailField(default='no-reply@makesamai.com', editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='email',
            name='message',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='subject',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='to_email',
            field=models.EmailField(editable=False, max_length=200),
        ),
    ]
