# Generated by Django 2.0 on 2018-04-06 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_auto_20180327_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account'),
        ),
        migrations.AlterField(
            model_name='email',
            name='from_email',
            field=models.EmailField(default='no-reply@makesamai.com', max_length=200),
        ),
        migrations.AlterField(
            model_name='email',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='to_email',
            field=models.EmailField(max_length=200),
        ),
    ]
