# Generated by Django 2.0 on 2018-05-15 19:18

from django.db import migrations, models
import django.db.models.deletion
import randomslugfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180405_1112'),
        ('emails', '0003_auto_20180406_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCampaign',
            fields=[
                ('cmid', randomslugfield.fields.RandomSlugField(blank=True, editable=False, length=9, max_length=9, primary_key=True, serialize=False, unique=True)),
                ('list', models.TextField(blank=True, null=True)),
                ('campaign_title', models.CharField(blank=True, max_length=255, null=True)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('message_template', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account')),
            ],
            options={
                'verbose_name_plural': 'Campaigns',
                'verbose_name': 'Campaign',
            },
        ),
    ]
