# Generated by Django 2.0 on 2018-05-19 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0006_emailcampaign_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emails.EmailCampaign'),
        ),
    ]
