# Generated by Django 2.0.2 on 2018-03-09 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='uuid',
            new_name='ucid',
        ),
    ]
