# Generated by Django 2.0 on 2018-03-26 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing_pages', '0001_initial'),
        ('forms', '0001_initial'),
        ('contacts', '0002_auto_20180309_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.Form'),
        ),
        migrations.AddField(
            model_name='contact',
            name='landing_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='landing_pages.LandingPage'),
        ),
    ]
