# Generated by Django 2.0 on 2018-03-25 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import randomslugfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_auto_20180309_1639'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('ufid', randomslugfield.fields.RandomSlugField(blank=True, editable=False, length=7, max_length=7, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('title_enabled', models.BooleanField(default=False)),
                ('title_required', models.BooleanField(default=False)),
                ('fname_enabled', models.BooleanField(default=True)),
                ('fname_required', models.BooleanField(default=False)),
                ('lname_enabled', models.BooleanField(default=True)),
                ('lname_required', models.BooleanField(default=False)),
                ('email_enabled', models.BooleanField(default=True)),
                ('email_required', models.BooleanField(default=True)),
                ('company_enabled', models.BooleanField(default=False)),
                ('company_required', models.BooleanField(default=False)),
                ('website_enabled', models.BooleanField(default=False)),
                ('website_required', models.BooleanField(default=False)),
                ('phone_enabled', models.BooleanField(default=False)),
                ('phone_required', models.BooleanField(default=False)),
                ('address_line_enabled', models.BooleanField(default=False)),
                ('address_line_required', models.BooleanField(default=False)),
                ('street_enabled', models.BooleanField(default=False)),
                ('street_required', models.BooleanField(default=False)),
                ('city_enabled', models.BooleanField(default=False)),
                ('city_required', models.BooleanField(default=False)),
                ('state_enabled', models.BooleanField(default=False)),
                ('state_required', models.BooleanField(default=False)),
                ('postcode_enabled', models.BooleanField(default=False)),
                ('postcode_required', models.BooleanField(default=False)),
                ('country_enabled', models.BooleanField(default=False)),
                ('country_required', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Forms',
                'verbose_name': 'Form',
            },
        ),
    ]
