# Generated by Django 2.0.2 on 2018-03-09 07:07

from django.db import migrations, models
import django.utils.timezone
import randomslugfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('uid', randomslugfield.fields.RandomSlugField(blank=True, editable=False, length=7, max_length=7, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'accounts',
                'verbose_name': 'account',
            },
        ),
    ]
