# Generated by Django 2.0.2 on 2018-03-09 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='uid',
            new_name='uaid',
        ),
    ]
