# Generated by Django 2.0 on 2018-04-05 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180309_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='slug',
        ),
        migrations.AddField(
            model_name='account',
            name='domain',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
