# Generated by Django 2.0 on 2018-03-25 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import randomslugfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_auto_20180309_1639'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('ulid', randomslugfield.fields.RandomSlugField(blank=True, editable=False, length=7, max_length=7, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('brand_name', models.CharField(default='XYZ Company', max_length=255, verbose_name='Brand Name')),
                ('thank_you_message', models.TextField(default='Your Response Has Been Recorded, Thank You For Submitting the Form!')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lp_created_by', to=settings.AUTH_USER_MODEL)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lp_form', to='forms.Form')),
            ],
            options={
                'verbose_name_plural': 'Landing Pages',
                'verbose_name': 'Landing Page',
            },
        ),
    ]
