# Generated by Django 2.0 on 2018-03-27 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import randomslugfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0003_auto_20180326_1424'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_auto_20180309_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('ugid', randomslugfield.fields.RandomSlugField(blank=True, editable=False, length=7, max_length=7, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account')),
                ('assigned_contacts', models.ManyToManyField(blank=True, related_name='assigned_contacts_list', to='contacts.Contact')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Lists',
                'verbose_name': 'List',
            },
        ),
    ]
